---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: install php support for package
    apt:
      name: libapache2-mod-php 
      state: latest

  - name: install net-tools package
    apt:
      name: net-tools
      state: latest

  - name: install python3-update-manager package
    apt:
      name: python3-update-manager
      state: latest

  - name: install update-manager-core package
    apt:
      name: update-manager-core
      state: latest

