---

- hosts: all
  become: true
  tasks:

  - name: update repo & install apache2 and utility packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - net-tools
        - nano
        - lsof
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repo & install nginx and utility packages
    pacman:
      name: 
        - nginx
        - php
        - nano
        - net-tools
      state: latest
      update_cache: yes
    when: ansible_distribution == "Archlinux"
