---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Archlinux)
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: install updates (Debian and Unbuntu)
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and utility packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - net-tools
        - nano
        - lsof
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb packages (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba  and filezilla packages
    apt:
      name:
        - samba
        - filezilla
      state: latest
    when: ansible_distribution == "Ubuntu"
