---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Archlinux)
    tags: always
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: install updates (Debian and Unbuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: workstations
  become: true
  tasks:

  - name: install utilties on workstation packages
    tags: utilities
    package: 
      name: 
        - unzip
        - nano
        - sudo
        - net-tools
        - lsof
      
  - name: install terraform
    tags: utilities
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and utility packages
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - net-tools
        - nano
        - lsof
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache web_server
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache,apache2,ubuntu
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin dike@medicitng.com
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2 (Ubuntu)
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default htm file for site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb packages (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start and enable mariadb server
    tags: ubuntu,db,mariadb
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba and filezilla packages
    tags: samba
    apt:
      name:
        - samba
        - filezilla
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start samba file server
    tags: samba
    service:
      name: smbd
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
