  - name: install apache2 and utility packages
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - net-tools
        - nano
        - lsof
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache web_server
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change e-mail address for admin
    tags: apache,apache2,ubuntu
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin dike@medicitng.com
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2 (Ubuntu)
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default htm file for site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
