  - name: install mariadb packages (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start and enable mariadb server
    tags: ubuntu,db,mariadb
    service:
      name: mariadb
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
