  - name: install utilties on workstation packages
    tags: utilities
    package: 
      name: 
        - unzip
        - nano
        - sudo
        - net-tools
        - lsof
      
  - name: install terraform
    tags: utilities
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

